### PR TITLE
Add API method GetShippingLabel

### PR DESCRIPTION
**Pull request by ppp0**
AWS changed their shipping&handling policy

> Amazon Import/Export now uses UPS as the worldwide carrier for all incoming Import/Export job requests. You must use UPS as your carrier to send packages to AWS, and you must use the pre-paid shipping label generated by the AWS Import/Export Web Service Tool. You will not have to pay UPS for the shipping charges, because AWS will add these charges to the fee charged for processing your device. For more information, see Shipping Your Storage Device.

To generate this pre-paid shipping label, one can use the API

Add method according to http://docs.aws.amazon.com/AWSImportExport/latest/DG/WebGetShippingLabel.html

(if feasible)

### CODE REVIEW

**Comment by ppp0** [comment]
@tomaszdurka for your viewing pleasure

**Comment by tomaszdurka** [comment]
@ppp0 I browsed the code briefly and have some questions. Let's meetup and discuss - maybe Wednesday?

**Comment by njam** [comment]
Not needed

**Comment by ppp0** [comment]
May be it's a good idea to implement this, still. So far, I'm using AWS `AWSImportExportWebServiceTool-1.0.jar` (see https://aws.amazon.com/snowball/disk/tools/). Would be good to only use one tool.

Also, we could integrate the Pre-paid shipping label's PDF download.

Steps are:
- call the API's `GetShippingLabel` with the JobID
- download the PDF from the S3 bucket designated by the Job's manifest
- (trickier) send it to the printer to be printed twice

**Comment by kris-lab** [comment]
As discussed with @ppp0 let's close it for the moment.

**Pull request closed without merging**
