### PR TITLE
Add local config file for easier sandboxing/development

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@ppp0 please review

**Comment by ppp0** [comment]
looks good - except for line23 (formatting? shouldn't a single closing parenthesis be aligned to line 10?

**Comment by tomaszdurka** [comment]
This is how it is formatted. Same way as in https://github.com/tomaszdurka/s3export_backup/blob/issue-8/resources/config/default.php. I guess we could put that extra bracket to next line, but is it gonna be cleaner? Not sure.

**Comment by tomaszdurka** [comment]
Wdyt about leaving as is?

**Comment by ppp0** [comment]
lgtm

**Pull request merged**
