### PR TITLE
Write Readme

### PR DESCRIPTION
**Pull request by tomaszdurka**
- Install
- Usage
- Test result interpretation (Number of Not founds vs wrong checksum)

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@ppp0 @njam please review / hint

**Comment by njam** [comment]
- Use dash-syntax for h2
```
My Header
---------
```
- How about not bother with "manual installation", but rather provide a `Vagrantfile` so anybody can get a working setup within minutes?
- I would expect specific instructions on the following two scenarios. How about describing them step by step?
 - Create job to send disk
 - Receive disk and verify

**Comment by ppp0** [comment]
I am doing a revision, please hang on

**Comment by ppp0** [comment]
* @njam `Vagrantfile` is a good idea!
* What about moving `./resources/config/local.php` to a more private place like the maintainer's root? May be symlink local.php from something like `~/.s3export_backup.conf` ?

**Comment by njam** [comment]
`resources/config/local.php` should not be part of this repo, it's actually git-ignored. There's `config/default.php` which contains the base configuration. On the other hand `local.php` should be used for specific environment configuration (database name, filesystem path, etc).

**Comment by ppp0** [comment]
I understand the mechanics of `local.php`, ti just doesn't look very common to me that you need to configure a software package by changing things in `/usr/local/lib/...`

**Comment by njam** [comment]
Agree. Since we're the only users for now I think we can live with it.

Otherwise there would need to be a "config path" configuration. Since the configuration file can be in different places depending on the OS?

**Comment by ppp0** [comment]
Somewhat agree. 
> Since the configuration file can be in different places depending on the OS?

It's debian (or linux) only anyway

>Since we're the only users for now

So you don't want to get people using this tool? :)

**Comment by njam** [comment]
Problem is just that this is a CM issue. We would need to make configuration file path *configurable* there?

**Comment by tomaszdurka** [comment]
Paired with @ppp0 please verify @ppp0 :)

**Comment by tomaszdurka** [comment]
@njam please review

**Comment by njam** [comment]
Looks very good!

One thing: Link the text "example manifest" to the file in the repo?

**Comment by tomaszdurka** [comment]
Changed the link, merging!

**Pull request merged**
